modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="extrabossrush"
version="1.0.0"
displayName="ExtraBossRush"
authors="tasogare_rui"
description='''${mod_description}'''

[[dependencies.extrabossrush]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extrabossrush]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
